package FuncionesBW;


import java.awt.Color;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erikv
 */
public class MainBW extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    
    public MainBW() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        CABECERA.setBackground(new Color(0,0,0,0));
        Header.setBackground(new Color(0,0,0,0));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FONDO = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();
        CABECERA = new javax.swing.JPanel();
        LogoBW = new javax.swing.JLabel();
        TextLogoBW = new javax.swing.JLabel();
        Principal = new javax.swing.JLabel();
        Perfil = new javax.swing.JLabel();
        SobreNosotros = new javax.swing.JLabel();
        SubirPublicacion = new javax.swing.JLabel();
        FondoBlanco = new javax.swing.JLabel();
        FondoVerde = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        setUndecorated(true);
        setResizable(false);

        FONDO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeaderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelExit.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPrincipal/Close.png"))); // NOI18N
        jLabelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelExit.setFocusable(false);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        Header.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1495, -10, 16, 46));

        FONDO.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1510, 40));

        CABECERA.setBackground(new java.awt.Color(255, 255, 255));
        CABECERA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoBW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPrincipal/LOGOBW.png"))); // NOI18N
        LogoBW.setText("jLabel1");
        CABECERA.add(LogoBW, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 77, 72));

        TextLogoBW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPrincipal/TEXT BW.png"))); // NOI18N
        CABECERA.add(TextLogoBW, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 60, 135, 45));

        Principal.setFont(new java.awt.Font("Jockey One", 0, 32)); // NOI18N
        Principal.setText("Principal");
        CABECERA.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 60, 105, 45));

        Perfil.setFont(new java.awt.Font("Jockey One", 0, 32)); // NOI18N
        Perfil.setText("Perfil");
        CABECERA.add(Perfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(789, 60, 68, 45));

        SobreNosotros.setFont(new java.awt.Font("Jockey One", 0, 32)); // NOI18N
        SobreNosotros.setText("Sobre Nosotros");
        CABECERA.add(SobreNosotros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1242, 60, 178, 45));

        SubirPublicacion.setFont(new java.awt.Font("Jockey One", 0, 32)); // NOI18N
        SubirPublicacion.setText("Subir Publicación");
        CABECERA.add(SubirPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 60, 202, 45));

        FONDO.add(CABECERA, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 1488, 150));

        FondoBlanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPrincipal/FondoBlanco.png"))); // NOI18N
        FondoBlanco.setText("jLabel1");
        FondoBlanco.setPreferredSize(new java.awt.Dimension(1488, 956));
        FONDO.add(FondoBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 1488, 956));

        FondoVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPrincipal/FondoVerde.png"))); // NOI18N
        FondoVerde.setPreferredSize(new java.awt.Dimension(1512, 892));
        FONDO.add(FondoVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1512, 982));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FONDO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HeaderMouseClicked

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y-yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainBW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainBW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainBW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainBW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainBW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CABECERA;
    private javax.swing.JPanel FONDO;
    private javax.swing.JLabel FondoBlanco;
    private javax.swing.JLabel FondoVerde;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LogoBW;
    private javax.swing.JLabel Perfil;
    private javax.swing.JLabel Principal;
    private javax.swing.JLabel SobreNosotros;
    private javax.swing.JLabel SubirPublicacion;
    private javax.swing.JLabel TextLogoBW;
    private javax.swing.JLabel jLabelExit;
    // End of variables declaration//GEN-END:variables
}
