/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ADMIN;

/**
 *
 * @author erikv
 */
public class AdminMainInterface extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainInterface
     */
    public AdminMainInterface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        VerUsuariosBoton = new javax.swing.JButton();
        BuscarUsuarioBoton = new javax.swing.JButton();
        EliminarUsuariosBoton = new javax.swing.JButton();
        CambiarDatosBoton = new javax.swing.JButton();
        CrearUsuarioBoton = new javax.swing.JButton();
        BirdWatch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(66, 66, 66));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo Birdwatch Login.png"))); // NOI18N

        VerUsuariosBoton.setText("Ver Usuarios");
        VerUsuariosBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerUsuariosBotonMouseClicked(evt);
            }
        });

        BuscarUsuarioBoton.setText("Buscar Usuario");
        BuscarUsuarioBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuscarUsuarioBotonMouseClicked(evt);
            }
        });

        EliminarUsuariosBoton.setText("Eliminar Usuario");
        EliminarUsuariosBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarUsuariosBotonMouseClicked(evt);
            }
        });

        CambiarDatosBoton.setText("Cambiar Datos Usuario");
        CambiarDatosBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CambiarDatosBotonMouseClicked(evt);
            }
        });
        CambiarDatosBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarDatosBotonActionPerformed(evt);
            }
        });

        CrearUsuarioBoton.setText("Crear Usuario");
        CrearUsuarioBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuarioBotonMouseClicked(evt);
            }
        });
        CrearUsuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBotonActionPerformed(evt);
            }
        });

        BirdWatch.setFont(new java.awt.Font("Jockey One", 0, 36)); // NOI18N
        BirdWatch.setForeground(new java.awt.Color(0, 215, 70));
        BirdWatch.setText("BIRDWATCH");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CambiarDatosBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscarUsuarioBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VerUsuariosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarUsuariosBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CrearUsuarioBoton)
                        .addGap(210, 210, 210))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(BirdWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Logo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(BirdWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CambiarDatosBoton)
                    .addComponent(VerUsuariosBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscarUsuarioBoton)
                    .addComponent(EliminarUsuariosBoton))
                .addGap(18, 18, 18)
                .addComponent(CrearUsuarioBoton)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambiarDatosBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarDatosBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiarDatosBotonActionPerformed

    private void CrearUsuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearUsuarioBotonActionPerformed

    private void CambiarDatosBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CambiarDatosBotonMouseClicked
       this.setVisible(false);
       CambiarDatos cambiarDatos = new CambiarDatos();
       cambiarDatos.setVisible(true);
    }//GEN-LAST:event_CambiarDatosBotonMouseClicked

    private void VerUsuariosBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerUsuariosBotonMouseClicked
        this.setVisible(false);
       VerUsuarios verUsuarios = new VerUsuarios();
       verUsuarios.setVisible(true);
    }//GEN-LAST:event_VerUsuariosBotonMouseClicked

    private void EliminarUsuariosBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarUsuariosBotonMouseClicked
        this.setVisible(false);
       EliminarUsuario eliminarUsuario = new EliminarUsuario();
       eliminarUsuario.setVisible(true);
    }//GEN-LAST:event_EliminarUsuariosBotonMouseClicked

    private void CrearUsuarioBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuarioBotonMouseClicked
        this.setVisible(false);
       CrearUsuario crearUsuario = new CrearUsuario();
       crearUsuario.setVisible(true);    }//GEN-LAST:event_CrearUsuarioBotonMouseClicked

    private void BuscarUsuarioBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarUsuarioBotonMouseClicked
        this.setVisible(false);
       BuscarUsuario buscar = new BuscarUsuario();
       buscar.setVisible(true);    }//GEN-LAST:event_BuscarUsuarioBotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BirdWatch;
    private javax.swing.JButton BuscarUsuarioBoton;
    private javax.swing.JButton CambiarDatosBoton;
    private javax.swing.JButton CrearUsuarioBoton;
    private javax.swing.JButton EliminarUsuariosBoton;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton VerUsuariosBoton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
