
import ArchivoPlano.EscribirArchivoPlano;
import ArchivoPlano.Seguridad;
import Clases.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erikv
 */
public class CrearCuenta extends javax.swing.JFrame {

    /**
     * Creates new form CrearCuenta
     */int xMouse, yMouse;
     Color grisClaro = new Color(176,176,176);
     Color grisOscuro = new Color(85,84,84);
    public CrearCuenta() {
            initComponents();
        this.setLocationRelativeTo(null);
        Nombre.setBackground(new java.awt.Color(0,0,0,1));
        Apellidos.setBackground(new java.awt.Color(0,0,0,1));
        TxtUsuario.setBackground(new java.awt.Color(0,0,0,1));
        CorreoElectronico.setBackground(new java.awt.Color(0,0,0,1));
        Contraseña.setBackground(new java.awt.Color(0,0,0,1));
        RepetirContraseña.setBackground(new java.awt.Color(0,0,0,1));
        Header.setBackground(new java.awt.Color(0,0,0,1));
        Cerrar.setBackground(new java.awt.Color(0,0,0,1));
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        BirdWatch1 = new javax.swing.JLabel();
        RepetirContraseña = new javax.swing.JPasswordField();
        Contraseña = new javax.swing.JPasswordField();
        Apellidos = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        TxtUsuario = new javax.swing.JTextField();
        CorreoElectronico = new javax.swing.JTextField();
        TermsAndConditions = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        IniciarSesionButton = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelClave = new javax.swing.JLabel();
        jLabelRepetirClave = new javax.swing.JLabel();
        ConCuenta = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Header = new javax.swing.JPanel();
        Cerrar = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 832));
        setUndecorated(true);
        setResizable(false);

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setMaximumSize(new java.awt.Dimension(1280, 832));
        Content.setMinimumSize(new java.awt.Dimension(1280, 832));
        Content.setPreferredSize(new java.awt.Dimension(1280, 832));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BirdWatch1.setFont(new java.awt.Font("Jockey One", 0, 64)); // NOI18N
        BirdWatch1.setForeground(new java.awt.Color(255, 255, 255));
        BirdWatch1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BirdWatch1.setText("BIRDWATCH");
        BirdWatch1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Content.add(BirdWatch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 390, 340, 70));

        RepetirContraseña.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        RepetirContraseña.setForeground(new java.awt.Color(176, 176, 176));
        RepetirContraseña.setText("**********");
        RepetirContraseña.setToolTipText("Contraseña");
        RepetirContraseña.setBorder(null);
        RepetirContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepetirContraseñaMouseClicked(evt);
            }
        });
        RepetirContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepetirContraseñaActionPerformed(evt);
            }
        });
        RepetirContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RepetirContraseñaKeyPressed(evt);
            }
        });
        Content.add(RepetirContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 513, 430, 30));

        Contraseña.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(176, 176, 176));
        Contraseña.setText("**********");
        Contraseña.setToolTipText("Contraseña");
        Contraseña.setBorder(null);
        Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContraseñaMouseClicked(evt);
            }
        });
        Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaActionPerformed(evt);
            }
        });
        Contraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContraseñaKeyPressed(evt);
            }
        });
        Content.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 439, 430, 30));

        Apellidos.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        Apellidos.setForeground(new java.awt.Color(176, 176, 176));
        Apellidos.setText("Apellidos");
        Apellidos.setToolTipText("Usuario");
        Apellidos.setBorder(null);
        Apellidos.setCaretColor(new java.awt.Color(0, 204, 0));
        Apellidos.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Apellidos.setSelectionColor(new java.awt.Color(0, 204, 0));
        Apellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApellidosMouseClicked(evt);
            }
        });
        Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosActionPerformed(evt);
            }
        });
        Content.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 291, 430, 30));

        Nombre.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        Nombre.setForeground(new java.awt.Color(176, 176, 176));
        Nombre.setText("Nombre");
        Nombre.setToolTipText("Usuario");
        Nombre.setBorder(null);
        Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Nombre.setSelectionColor(new java.awt.Color(0, 204, 0));
        Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombreMouseClicked(evt);
            }
        });
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        Content.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 217, 150, 30));

        TxtUsuario.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        TxtUsuario.setForeground(new java.awt.Color(176, 176, 176));
        TxtUsuario.setText("Usuario");
        TxtUsuario.setToolTipText("Usuario");
        TxtUsuario.setBorder(null);
        TxtUsuario.setCaretColor(new java.awt.Color(0, 204, 0));
        TxtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtUsuario.setSelectionColor(new java.awt.Color(0, 204, 0));
        TxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtUsuarioMouseClicked(evt);
            }
        });
        TxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioActionPerformed(evt);
            }
        });
        Content.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1032, 217, 180, 30));

        CorreoElectronico.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        CorreoElectronico.setForeground(new java.awt.Color(176, 176, 176));
        CorreoElectronico.setText("Correo Electrónico");
        CorreoElectronico.setToolTipText("Contraseña");
        CorreoElectronico.setBorder(null);
        CorreoElectronico.setCaretColor(new java.awt.Color(0, 204, 0));
        CorreoElectronico.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        CorreoElectronico.setSelectionColor(new java.awt.Color(0, 204, 0));
        CorreoElectronico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CorreoElectronicoMouseClicked(evt);
            }
        });
        CorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoElectronicoActionPerformed(evt);
            }
        });
        Content.add(CorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 365, 430, 30));

        TermsAndConditions.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        TermsAndConditions.setForeground(new java.awt.Color(255, 255, 255));
        TermsAndConditions.setText("Provacy policy and terms of service");
        TermsAndConditions.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Content.add(TermsAndConditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 770, 331, 52));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Green Gradient Background.png"))); // NOI18N
        Content.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 641, 832));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo Birdwatch Login.png"))); // NOI18N
        Content.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(919, 49, 122, 126));

        IniciarSesionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Iniciar Sesion Button.png"))); // NOI18N
        IniciarSesionButton.setBorder(null);
        IniciarSesionButton.setBorderPainted(false);
        IniciarSesionButton.setContentAreaFilled(false);
        IniciarSesionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesionButton.setDefaultCapable(false);
        IniciarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionButtonActionPerformed(evt);
            }
        });
        Content.add(IniciarSesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 412, 65));

        jLabelNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesCrearCuenta/NombreBox.png"))); // NOI18N
        Content.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 208, 236, 49));

        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesCrearCuenta/UsuarioBox.png"))); // NOI18N
        Content.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 208, 400, 49));

        jLabelApellidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesCrearCuenta/ApellidosBox.png"))); // NOI18N
        Content.add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 282, 518, 49));

        jLabelCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesCrearCuenta/CorreoBox.png"))); // NOI18N
        Content.add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 356, 518, 49));

        jLabelClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesCrearCuenta/ContraseñaBox.png"))); // NOI18N
        Content.add(jLabelClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 430, 518, 49));

        jLabelRepetirClave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesCrearCuenta/ContraseñaBox.png"))); // NOI18N
        Content.add(jLabelRepetirClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 504, 518, 49));

        ConCuenta.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        ConCuenta.setForeground(new java.awt.Color(0, 99, 249));
        ConCuenta.setText("¿Ya tienes una cuenta? Haz click aquí.");
        ConCuenta.setBorder(null);
        ConCuenta.setBorderPainted(false);
        ConCuenta.setContentAreaFilled(false);
        ConCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConCuentaActionPerformed(evt);
            }
        });
        Content.add(ConCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 680, -1, -1));

        jTextField1.setText("jTextField1");
        Content.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Content.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 40));

        jLabelCerrar.setFont(new java.awt.Font("Inter Thin", 1, 32)); // NOI18N
        jLabelCerrar.setForeground(new java.awt.Color(0, 204, 0));
        jLabelCerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCerrar.setText("x");
        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CerrarLayout = new javax.swing.GroupLayout(Cerrar);
        Cerrar.setLayout(CerrarLayout);
        CerrarLayout.setHorizontalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CerrarLayout.setVerticalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarLayout.createSequentialGroup()
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        Content.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioActionPerformed

    private void CorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoElectronicoActionPerformed

    private void IniciarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionButtonActionPerformed
        if(!campoVacio()){

            String usuario = TxtUsuario.getText();
            
            if (Seguridad.usuarioRepetido(usuario)) {
                String nombre = Nombre.getText();
                String apellidos = Apellidos.getText();
                String correoElectronico = CorreoElectronico.getText();
                String password;
                password = String.copyValueOf(Contraseña.getPassword());
                EscribirArchivoPlano.escribir(usuario, password, correoElectronico, nombre, apellidos);
                JOptionPane.showMessageDialog(this, "Cuenta creada");
                Login abrir = new Login();
                this.setVisible(false);
                abrir.setVisible(true);
                
            }
            
            else{
                JOptionPane.showMessageDialog(this, "El nombre de usuario - "+TxtUsuario.getText()+" - ya existe, por favor pruebe uno nuevo");
                TxtUsuario.setText("Usuario");
                TxtUsuario.setForeground(grisClaro);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos");
        }
        
        
    }//GEN-LAST:event_IniciarSesionButtonActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidosActionPerformed

    private void ConCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConCuentaActionPerformed
       this.setVisible(false);
       Login log = new Login();
       log.setVisible(true);
       
    }//GEN-LAST:event_ConCuentaActionPerformed

    private void NombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreMouseClicked
        estadoOriginal();
        if (Nombre.getText().equals("Nombre")) {
            Nombre.setText("");
            Nombre.setForeground(grisOscuro);
        }
    }//GEN-LAST:event_NombreMouseClicked

    private void TxtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtUsuarioMouseClicked
        estadoOriginal();
        if (TxtUsuario.getText().equals("Usuario")) {
           TxtUsuario.setText("");
           TxtUsuario.setForeground(grisOscuro); 
        }
        
        
    }//GEN-LAST:event_TxtUsuarioMouseClicked

    private void ApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApellidosMouseClicked
        estadoOriginal();
        if (Apellidos.getText().equals("Apellidos")) {
            Apellidos.setText("");
            Apellidos.setForeground(grisOscuro);
        }
        
    }//GEN-LAST:event_ApellidosMouseClicked

    private void CorreoElectronicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreoElectronicoMouseClicked
        estadoOriginal();
        if (CorreoElectronico.getText().equals("Correo Electrónico")) {
            CorreoElectronico.setText("");
            CorreoElectronico.setForeground(grisOscuro);
        }
        
    }//GEN-LAST:event_CorreoElectronicoMouseClicked

    private void ContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContraseñaMouseClicked
        estadoOriginal();
        if(String.valueOf(Contraseña.getPassword()).equals("**********"))
            Contraseña.setText("");
            Contraseña.setForeground(grisOscuro);

    }//GEN-LAST:event_ContraseñaMouseClicked

    private void ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaActionPerformed

    private void ContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaKeyPressed

    }//GEN-LAST:event_ContraseñaKeyPressed

    private void RepetirContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepetirContraseñaMouseClicked
        estadoOriginal();
        if(String.valueOf(RepetirContraseña.getPassword()).equals("**********"))
            RepetirContraseña.setText("");
            RepetirContraseña.setForeground(grisOscuro);
    }//GEN-LAST:event_RepetirContraseñaMouseClicked

    private void RepetirContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepetirContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepetirContraseñaActionPerformed

    private void RepetirContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RepetirContraseñaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepetirContraseñaKeyPressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y-yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCerrarMouseClicked
    
    private boolean campoVacio(){
        if(Nombre.getText().equals("Nombre") || Nombre.getText().isEmpty()){
            return true;
        }
        if(TxtUsuario.getText().equals("Usuario") || TxtUsuario.getText().isEmpty()){
            return true;
        }
        if(Apellidos.getText().equals("Apellidos") || Apellidos.getText().isEmpty()){
            return true;
        }
        if(CorreoElectronico.getText().equals("Correo") || CorreoElectronico.getText().isEmpty()){
            return true;
        }
        if (Contraseña.getPassword().equals("**********") || String.valueOf(Contraseña.getPassword()).isEmpty()){
            return true;
        }
        if (RepetirContraseña.getPassword().equals("**********") || String.valueOf(RepetirContraseña.getPassword()).isEmpty()){
            return true;
        }
        return false;
    }
    
    private void estadoOriginal (){
        if (Nombre.getText().isEmpty()) {
            Nombre.setText("Nombre");
            Nombre.setForeground(grisClaro);
        }
        
        if (TxtUsuario.getText().isEmpty()) {
            TxtUsuario.setText("Usuario");
            TxtUsuario.setForeground(grisClaro);
        }
        
        if (Apellidos.getText().isEmpty()) {
            Apellidos.setText("Apellidos");
            Apellidos.setForeground(grisClaro);
        }
        
        
        if (CorreoElectronico.getText().isEmpty()) {
            CorreoElectronico.setText("Correo Electrónico");
            CorreoElectronico.setForeground(grisClaro);
        }
        
        
        if (String.valueOf(Contraseña.getPassword()).isEmpty()) {
            Contraseña.setText("**********");
            Contraseña.setForeground(grisClaro);
        }
        
        
        if (String.valueOf(RepetirContraseña.getPassword()).isEmpty()) {
            RepetirContraseña.setText("**********");
            RepetirContraseña.setForeground(grisClaro);
        }
        
        
        
        
        
        
        
    }/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellidos;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BirdWatch1;
    private javax.swing.JPanel Cerrar;
    private javax.swing.JButton ConCuenta;
    private javax.swing.JPanel Content;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JTextField CorreoElectronico;
    private javax.swing.JPanel Header;
    private javax.swing.JButton IniciarSesionButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField Nombre;
    private javax.swing.JPasswordField RepetirContraseña;
    private javax.swing.JLabel TermsAndConditions;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelClave;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRepetirClave;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
