
import FuncionesBW.MainBW;
import ArchivoPlano.Seguridad;

import java.awt.Color;
import java.util.Scanner;
import javax.swing.JOptionPane;







/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author erikv
 */
public class Login extends javax.swing.JFrame {
    private static Scanner sc;
    private static int intentos;
    private static String user,pass;

    /**
     * Creates new form Login
     */
    int xMouse;
    int yMouse;
    Color grisClaro = new Color(176,176,176);
    Color grisOscuro = new Color(85,84,84);

    public Login() {
        initComponents();
       this.setLocationRelativeTo(null);       
       txtUsuario.setBackground(new java.awt.Color(0,0,0,1));
       Cerrar.setBackground(new java.awt.Color(0,0,0,1));
       Header.setBackground(new java.awt.Color(0,0,0,1));
       jPassword.setBackground(new java.awt.Color(0,0,0,1));
       


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        txtUsuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        TermsAndConditions = new javax.swing.JLabel();
        BirdWatch = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        UsuarioBox = new javax.swing.JLabel();
        ContrasenaBox = new javax.swing.JLabel();
        IniciarSesionButton = new javax.swing.JButton();
        SinCuenta = new javax.swing.JButton();
        Cerrar = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Content.setMaximumSize(new java.awt.Dimension(1280, 832));
        Content.setMinimumSize(new java.awt.Dimension(1280, 832));
        Content.setPreferredSize(new java.awt.Dimension(1280, 832));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        Content.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 40));

        txtUsuario.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(176, 176, 176));
        txtUsuario.setText("Usuario");
        txtUsuario.setToolTipText("Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.setSelectionColor(new java.awt.Color(0, 204, 0));
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        Content.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 285, 332, 30));

        jPassword.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        jPassword.setForeground(new java.awt.Color(176, 176, 176));
        jPassword.setText("**********");
        jPassword.setToolTipText("Contraseña");
        jPassword.setBorder(null);
        jPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordMouseClicked(evt);
            }
        });
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordKeyPressed(evt);
            }
        });
        Content.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 387, 332, 30));

        TermsAndConditions.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        TermsAndConditions.setForeground(new java.awt.Color(255, 255, 255));
        TermsAndConditions.setText("Provacy policy and terms of service");
        TermsAndConditions.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Content.add(TermsAndConditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 770, 331, 52));

        BirdWatch.setFont(new java.awt.Font("Jockey One", 0, 64)); // NOI18N
        BirdWatch.setForeground(new java.awt.Color(255, 255, 255));
        BirdWatch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BirdWatch.setText("BIRDWATCH");
        BirdWatch.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Content.add(BirdWatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 390, 340, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Green Gradient Background.png"))); // NOI18N
        Content.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 641, 832));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo Birdwatch Login.png"))); // NOI18N
        Content.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(929, 55, 122, 126));

        UsuarioBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Usuario Box.png"))); // NOI18N
        Content.add(UsuarioBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 276, 440, 49));

        ContrasenaBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Password Box.png"))); // NOI18N
        Content.add(ContrasenaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 378, 440, 49));

        IniciarSesionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Iniciar Sesion Button.png"))); // NOI18N
        IniciarSesionButton.setBorder(null);
        IniciarSesionButton.setBorderPainted(false);
        IniciarSesionButton.setContentAreaFilled(false);
        IniciarSesionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniciarSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionButtonActionPerformed(evt);
            }
        });
        Content.add(IniciarSesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 502, 412, 65));

        SinCuenta.setFont(new java.awt.Font("Jockey One", 0, 20)); // NOI18N
        SinCuenta.setForeground(new java.awt.Color(0, 99, 249));
        SinCuenta.setText("¿Aún no tienes cuenta? Haz click aquí.");
        SinCuenta.setBorder(null);
        SinCuenta.setBorderPainted(false);
        SinCuenta.setContentAreaFilled(false);
        SinCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SinCuentaActionPerformed(evt);
            }
        });
        Content.add(SinCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 593, -1, -1));

        Exit.setFont(new java.awt.Font("Inter Thin", 1, 32)); // NOI18N
        Exit.setForeground(new java.awt.Color(0, 204, 0));
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("x");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CerrarLayout = new javax.swing.GroupLayout(Cerrar);
        Cerrar.setLayout(CerrarLayout);
        CerrarLayout.setHorizontalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CerrarLayout.setVerticalGroup(
            CerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CerrarLayout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        Content.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, -1, 40));

        jTextField1.setText("jTextField1");
        Content.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionButtonActionPerformed
    String usuario = txtUsuario.getText();
    String clave = String.copyValueOf(jPassword.getPassword());
        if (Seguridad.ingresarCuenta(usuario, clave)) {
            MainBW abrir = new MainBW();
            this.setVisible(false);
            abrir.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Uuuario o Clave incorrecta");
        }
    
       
    }//GEN-LAST:event_IniciarSesionButtonActionPerformed

    private void SinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SinCuentaActionPerformed
       this.setVisible(false);
       CrearCuenta cC = new CrearCuenta();
       cC.setVisible(true);
    }//GEN-LAST:event_SinCuentaActionPerformed

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y-yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordKeyPressed
        
    }//GEN-LAST:event_jPasswordKeyPressed

    private void jPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordMouseClicked
        if (txtUsuario.getText().isEmpty()) {
            txtUsuario.setText("Usuario");
        txtUsuario.setForeground(grisClaro);
        }
        
        if (String.valueOf(jPassword.getPassword()).equals("**********")) {
            jPassword.setText("");
        jPassword.setForeground(grisOscuro);
        }
        
    }//GEN-LAST:event_jPasswordMouseClicked

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed

    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        if(txtUsuario.getText().equals("Usuario")){
            txtUsuario.setText("");
            txtUsuario.setForeground(grisOscuro);
        }
        if(String.valueOf(jPassword.getPassword()).isEmpty()){
            jPassword.setText("**********");
            jPassword.setForeground(grisClaro);
        }
    }//GEN-LAST:event_txtUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BirdWatch;
    private javax.swing.JPanel Cerrar;
    private javax.swing.JPanel Content;
    private javax.swing.JLabel ContrasenaBox;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel Header;
    private javax.swing.JButton IniciarSesionButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton SinCuenta;
    private javax.swing.JLabel TermsAndConditions;
    private javax.swing.JLabel UsuarioBox;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
